name: CI/CD Pipeline

on:
  pull_request:
    branches: [main]

jobs:
  pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Node.js and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Cache Yarn cache
        uses: actions/cache@v2
        with:
          path: ~/.yarn/cache
          key: yarn-${{ runner.OS }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-${{ runner.OS }}-

      - name: Install Dependencies
        run: yarn install --immutable

  lint:
    needs: pipeline
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Restore Cached Yarn cache
        uses: actions/cache@v2
        with:
          path: ~/.yarn/cache
          key: yarn-${{ runner.OS }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-${{ runner.OS }}-

      - name: Lint
        run: yarn lint

  test:
    needs: lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Restore Cached Yarn cache
        uses: actions/cache@v2
        with:
          path: ~/.yarn/cache
          key: yarn-${{ runner.OS }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-${{ runner.OS }}-

      - name: Test
        run: yarn test

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Restore Cached Yarn cache
        uses: actions/cache@v2
        with:
          path: ~/.yarn/cache
          key: yarn-${{ runner.OS }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            yarn-${{ runner.OS }}-

      - name: Build
        run: yarn build
